# Generated by Django 3.1.1 on 2020-10-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='passed',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('na', 'N/A')], default='text', max_length=3),
            preserve_default=False,
        ),
    ]
