# Generated by Django 3.1.1 on 2020-10-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_progress_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='passed',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('na', 'N/A')], default='na', max_length=3),
        ),
    ]
