# Generated by Django 3.1.1 on 2020-10-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_auto_20201022_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='passed',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('NA', 'NOT APPLICABLE')], default='NA', max_length=20),
        ),
    ]
