# Generated by Django 3.1.1 on 2020-10-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_auto_20201022_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='passed',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('NA', 'NOT APPLICABLE')], max_length=20, null=True),
        ),
    ]
