# Generated by Django 3.1.1 on 2020-09-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='name',
            new_name='title',
        ),
    ]
