# Generated by Django 3.1.1 on 2020-09-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0003_auto_20200924_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.TextField(),
        ),
    ]
