# Generated by Django 3.1.1 on 2020-10-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0004_auto_20200924_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('challenge', 'Challenge')], default='text', max_length=12),
            preserve_default=False,
        ),
    ]
