# Generated by Django 3.1.1 on 2020-11-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Classroom',
        ),
    ]
