# Generated by Django 3.1.1 on 2020-11-05 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_language', to='language.language')),
                ('new_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_language', to='language.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
